Importing the Libraries


In [ ]:
import numpy as np
import pandas as pd

Importing the dataset

In [ ]:
dataset = pd.read_csv('weather.csv')
X = dataset.iloc[:,[2,13]].values
Y = dataset.iloc[:,-1].values

In [ ]:
print(X)

[[22.9 22. ]
 [25.1 25. ]
 [25.7 30. ]
 ...
 [26.9 24. ]
 [27.  24. ]
 [ nan 36. ]]


In [ ]:
print(Y)

['No' 'No' 'No' ... 'No' 'No' nan]


In [ ]:
Y = Y.reshape(-1,1)

In [ ]:
print(Y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 [nan]]


Cleaning the data

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
X = imputer.fit_transform(X)
Y = imputer.fit_transform(Y)

Encoding data

In [ ]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
Y[:,-1] = le1.fit_transform(Y[:,-1])

In [ ]:
Y = np.array(Y,dtype=float)
print(Y)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [ ]:
print(X)

[[-0.04135977 -1.44365196]
 [ 0.26874452 -1.29710515]
 [ 0.35331842 -1.05286047]
 ...
 [ 0.52246622 -1.34595409]
 [ 0.53656187 -1.34595409]
 [-0.45013361 -0.75976686]]


Splitting dataset into training and testing

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [ ]:
print(X_train)

[[ 0.07140543  1.04764379]
 [ 0.11369237  0.16836293]
 [-0.14002932 -0.22242856]
 ...
 [ 0.93124006  0.119514  ]
 [-0.16822062 -0.12473068]
 [-0.91529006 -0.02703281]]


In [ ]:
print(Y_train)

[[1.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, Y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [ ]:
import time
start_time = time.time()
y_pred = le1.inverse_transform(np.array(lr.predict(X_test),dtype=int))
Y_test = le1.inverse_transform(np.array(Y_test,dtype=int))




/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:154: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y_pred = y_pred.reshape(-1,1)
Y_test = Y_test.reshape(-1,1)

In [ ]:
df = np.concatenate((Y_test,y_pred),axis=1)
dataframe = pd.DataFrame(df,columns=['Actual Result','Predition'])

In [ ]:
print(dataframe)
import time
end_time = time.time()
print(end_time - start_time)

      Actual Result Predition
0               Yes        No
1               Yes        No
2                No        No
3                No       Yes
4                No        No
...             ...       ...
29087            No        No
29088            No        No
29089           Yes        No
29090            No        No
29091            No        No

[29092 rows x 2 columns]
0.05294656753540039


In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

0.8249690636601128

Training the Model

In [ ]:
print(y_pred)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


In [ ]:
print(Y_test)

[['Yes']
 ['Yes']
 ['No']
 ...
 ['Yes']
 ['No']
 ['No']]


In [ ]:
X_pred = [[30.1, 27]]

In [ ]:
y_pred = le1.inverse_transform(np.array(lr.predict(X_pred),dtype=int))

In [ ]:
y_pred = y_pred.reshape(-1,1)

In [ ]:
print(X_pred)

[[30.1, 27]]


In [ ]:
print(y_pred)

[['Yes']]


In [ ]:
dataset = pd.read_csv('test.csv')
X_pred = dataset.iloc[:,[0,1]].values

In [ ]:
y_pred = le1.inverse_transform(np.array(lr.predict(X_pred),dtype=int))

In [ ]:
y_pred = y_pred.reshape(-1,1)


In [ ]:
print(y_pred)

[['Yes']
 ['Yes']
 ['Yes']
 ['Yes']
 ['Yes']
 ['Yes']
 ['Yes']
 ['Yes']
 ['Yes']
 ['Yes']
 ['Yes']
 ['Yes']
 ['Yes']
 ['Yes']
 ['Yes']
 ['Yes']
 ['Yes']
 ['Yes']
 ['Yes']
 ['Yes']]
